---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: h2
  name: h2
spec:
  image:
    name: calunga-tenant/h2

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: h2
spec:
  componentName: h2
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/h2
