---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: tox
  name: tox
spec:
  image:
    name: calunga-tenant/tox

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: tox
spec:
  componentName: tox
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/tox
