---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: trove-classifiers
  name: trove-classifiers
spec:
  image:
    name: calunga-tenant/trove-classifiers

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: trove-classifiers
spec:
  componentName: trove-classifiers
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/trove-classifiers
