---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: prompt-toolkit
  name: prompt-toolkit
spec:
  image:
    name: calunga-tenant/prompt-toolkit

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: prompt-toolkit
spec:
  componentName: prompt-toolkit
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/prompt-toolkit
