---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: grpcio-status
  name: grpcio-status
spec:
  image:
    name: calunga-tenant/grpcio-status

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: grpcio-status
spec:
  componentName: grpcio-status
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/grpcio-status
