---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: distlib
  name: distlib
spec:
  image:
    name: calunga-tenant/distlib

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: distlib
spec:
  componentName: distlib
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/distlib
