---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pytest
  name: pytest
spec:
  image:
    name: calunga-tenant/pytest

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pytest
spec:
  componentName: pytest
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pytest
