---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: botocore
  name: botocore
spec:
  image:
    name: calunga-tenant/botocore

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: botocore
spec:
  componentName: botocore
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/botocore
