---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: limits
  name: limits
spec:
  image:
    name: calunga-tenant/limits

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: limits
spec:
  componentName: limits
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/limits
