---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: fastavro
  name: fastavro
spec:
  image:
    name: calunga-tenant/fastavro

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: fastavro
spec:
  componentName: fastavro
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/fastavro
