---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: rfc3986-validator
  name: rfc3986-validator
spec:
  image:
    name: calunga-tenant/rfc3986-validator

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: rfc3986-validator
spec:
  componentName: rfc3986-validator
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/rfc3986-validator
