---
name: 🌱 Add Package
description: >
  Request that a new python package is added to this repository so Calunga will build it
  from source and publish it on its python index.
title: "Onboard package: [PACKAGE_NAME]"
body:
- type: input
  id: package
  attributes:
    label: Package name
    description: Name of the package to add
  validations:
    required: true
- type: textarea
  id: reason
  attributes:
    label: Reason
    description: Why do you want to add this package?
  validations:
    required: true
- type: checkboxes
  attributes:
    id: verified
    label: Verification
    description: >
      By submitting this issue, you agree to have verified the package is legitimate.
    options:
    - label: I agree
      required: true
