---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pathspec
  name: pathspec
spec:
  image:
    name: calunga-tenant/pathspec

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pathspec
spec:
  componentName: pathspec
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pathspec
