---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jupyter-events
  name: jupyter-events
spec:
  image:
    name: calunga-tenant/jupyter-events

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jupyter-events
spec:
  componentName: jupyter-events
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jupyter-events
