---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: types-psutil
  name: types-psutil
spec:
  image:
    name: calunga-tenant/types-psutil

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: types-psutil
spec:
  componentName: types-psutil
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/types-psutil
