---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: platformdirs
  name: platformdirs
spec:
  image:
    name: calunga-tenant/platformdirs

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: platformdirs
spec:
  componentName: platformdirs
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/platformdirs
