---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: packaging
  name: packaging
spec:
  image:
    name: calunga-tenant/packaging

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: packaging
spec:
  componentName: packaging
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/packaging
