---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: colorama
  name: colorama
spec:
  image:
    name: calunga-tenant/colorama

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: colorama
spec:
  componentName: colorama
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/colorama
