---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pluggy
  name: pluggy
spec:
  image:
    name: lucarval-tenant/pluggy

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pluggy
spec:
  componentName: pluggy
  containerImage: quay.io/redhat-user-workloads/lucarval-tenant/pluggy
