---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: hatchling
  name: hatchling
spec:
  image:
    name: calunga-tenant/hatchling

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hatchling
spec:
  componentName: hatchling
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/hatchling
