---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: marshmallow
  name: marshmallow
spec:
  image:
    name: lucarval-tenant/marshmallow

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: marshmallow
spec:
  componentName: marshmallow
  containerImage: quay.io/redhat-user-workloads/lucarval-tenant/marshmallow
