---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: ninja
  name: ninja
spec:
  image:
    name: calunga-tenant/ninja

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: ninja
spec:
  componentName: ninja
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/ninja
