---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: arrow
  name: arrow
spec:
  image:
    name: calunga-tenant/arrow

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: arrow
spec:
  componentName: arrow
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/arrow
