---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: mdurl
  name: mdurl
spec:
  image:
    name: calunga-tenant/mdurl

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: mdurl
spec:
  componentName: mdurl
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/mdurl
