---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pydantic
  name: pydantic
spec:
  image:
    name: calunga-tenant/pydantic

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pydantic
spec:
  componentName: pydantic
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pydantic
