---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: calver
  name: calver
spec:
  image:
    name: calunga-tenant/calver

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: calver
spec:
  componentName: calver
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/calver
