---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: hyperframe
  name: hyperframe
spec:
  image:
    name: calunga-tenant/hyperframe

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hyperframe
spec:
  componentName: hyperframe
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/hyperframe
