---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: readme-renderer
  name: readme-renderer
spec:
  image:
    name: calunga-tenant/readme-renderer

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: readme-renderer
spec:
  componentName: readme-renderer
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/readme-renderer
