---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: black
  name: black
spec:
  image:
    name: calunga-tenant/black

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: black
spec:
  componentName: black
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/black
