---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: django
  name: django
spec:
  image:
    name: lucarval-tenant/django

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: django
spec:
  componentName: django
  containerImage: quay.io/redhat-user-workloads/lucarval-tenant/django
