---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-on-boarding
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - components
      - imagerepositories
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
