---
name: Package Onboarding

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  onboard-package:
    if: github.event.label.name == 'on-board'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract package name from issue
        id: extract
        run: |
          # Extract package name from issue title
          PKG_NAME=$(echo "${{ github.event.issue.title }}" | sed -n 's/Onboard package: \([^]]*\)/\1/p')
          echo "package_name=$PKG_NAME" >> $GITHUB_OUTPUT

      - name: Create package directory and generate files
        run: |
          # Install python dependencies
          python -m pip install --upgrade "pip==23.3.2"
          python -m pip install pip-tools pybuild-deps

          # Debug information
          echo "Python version:"
          python --version
          echo "pip version:"
          pip --version
          echo "pip-tools version:"
          pip-compile --version
          echo "Python path:"
          which python
          echo "pip path:"
          which pip
          echo "pip-tools path:"
          which pip-compile

          mkdir "packages/${{ steps.extract.outputs.package_name }}"
          ./generate.sh

      - name: Apply Konflux resources
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENTS }}" > kubeconfig.yaml
          kustomize build "konflux/components/${{ steps.extract.outputs.package_name }}" | kubectl apply -f -
          rm -f kubeconfig.yaml
        env:
          KUBECONFIG: kubeconfig.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            packages/${{ steps.extract.outputs.package_name }}
            konflux
            .tekton
          branch: "on-board/${{ steps.extract.outputs.package_name }}"
          commit-message: "Onboard ${{ steps.extract.outputs.package_name }} package"
          title: "Onboard ${{ steps.extract.outputs.package_name }} package"
          body: |
            Fixes: #${{ github.event.issue.number }}
          sign-commits: true
          signoff: true
