---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: click
  name: click
spec:
  image:
    name: calunga-tenant/click

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: click
spec:
  componentName: click
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/click
