---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: httpcore
  name: httpcore
spec:
  image:
    name: calunga-tenant/httpcore

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: httpcore
spec:
  componentName: httpcore
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/httpcore
